### ISSUE TITLE
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by CubixSystem** [AtomLinter/linter-eslint#210]
#101 #99 strikes back!
```javascript
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at Function.wrapfunction (D:\Docs\Tests\crafty-test\node_modules\body-parser\node_modules\depd\index.js:421:5)
    at Object.<anonymous> (D:\Docs\Tests\crafty-test\node_modules\body-parser\index.js:37:46)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .js] (C:\Users\Redfox\AppData\Local\atom\app-1.0.11\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (D:\Docs\Tests\crafty-test\app.js:9:16)
    at Module._compile (module.js:452:26)
```
```D:\Docs\Tests\crafty-test\node_modules\body-parser\node_modules\depd\index.js:421:5``` contains this code:
```javascript
  var deprecatedfn = eval('(function (' + args + ') {\n'
    + '"use strict"\n'
    + 'log.call(deprecate, message, site)\n'
    + 'return fn.apply(this, arguments)\n'
    + '})')
```
Atom version: ```1.0.11```
linter-eslint version: ```3.0.2```

**Comment by PMK** [comment]
I got this too on Mac OSX:

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
  at Function (native)
  at createIterator (node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/lodash/dist/lodash.js:586:68)
  at node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/lodash/dist/lodash.js:609:14
  at Object.<anonymous> (node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/lodash/dist/lodash.js:4983:2)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:14:9)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:16:15)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:1:74)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (node_modules/gulp/node_modules/vinyl-fs/index.js:6:10)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (node_modules/gulp/index.js:7:11)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (node_modules/laravel-elixir/index.js:2:12)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (gulpfile.js:4:14)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at /Users/patrickk/.atom/packages/linter-eslint/node_modules/eslint/lib/load-rules.js:36:36
  at Array.forEach (native)
  at module.exports (/Users/patrickk/.atom/packages/linter-eslint/node_modules/eslint/lib/load-rules.js:32:30)
  at Object.load (/Users/patrickk/.atom/packages/linter-eslint/node_modules/eslint/lib/rules.js:42:20)
  at /Users/patrickk/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:271:19
  at Array.forEach (native)
  at new CLIEngine (/Users/patrickk/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:269:32)
  at Object.provider.lint (/Users/patrickk/.atom/packages/linter-eslint/lib/linter-eslint.coffee:85:24)
  at Promise.then._this.emitter.emit.linter (/Users/patrickk/.atom/packages/linter/lib/linter-registry.coffee:59:22)
  at LinterRegistry.triggerLinter (/Users/patrickk/.atom/packages/linter/lib/linter-registry.coffee:58:16)
  at /Users/patrickk/.atom/packages/linter/lib/linter-registry.coffee:52:17
  at Array.map (native)
  at /Users/patrickk/.atom/packages/linter/lib/linter-registry.coffee:50:27
```

OSX: `10.10.4`
Atom: `1.0.11`
linter-eslint: `3.0.2`

This error is being triggered when the setting "Eslint Rules Dir" is filled in and saving a JavaScript file. If the setting is empty, then this doesn't appear.

**Comment by jbmartinez** [comment]
I'm getting this too on Windows, regardless of the settings. I had to install eslint locally to get it working:

Windows 8.1
Atom: 1.0.19
linter-eslint: 3.2.0

**Comment by gfarrell** [comment]
Also seeing this issue on `OSX@10.11.1`; `Atom@1.0.19`; `linter-eslint@3.2.0`

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
  at Function (native)
  at Function.line.toFunction (/Users/gideon/.atom/packages/linter-eslint/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55:21)
  at compile (/Users/gideon/.atom/packages/linter-eslint/node_modules/eslint/node_modules/is-my-json-valid/index.js:543:23)
  at visit (/Users/gideon/.atom/packages/linter-eslint/node_modules/eslint/node_modules/is-my-json-valid/index.js:326:16)
  at /Users/gideon/.atom/packages/linter-eslint/node_modules/eslint/node_modules/is-my-json-valid/index.js:523:9
  at Array.forEach (native)
  at visit (/Users/gideon/.atom/packages/linter-eslint/node_modules/eslint/node_modules/is-my-json-valid/index.js:520:31)
  at compile (/Users/gideon/.atom/packages/linter-eslint/node_modules/eslint/node_modules/is-my-json-valid/index.js:537:3)
  at module.exports (/Users/gideon/.atom/packages/linter-eslint/node_modules/eslint/node_modules/is-my-json-valid/index.js:564:10)
  at Object.<anonymous> (/Users/gideon/.atom/packages/linter-eslint/node_modules/eslint/lib/testers/rule-tester.js:79:22)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/gideon/.atom/packages/linter-eslint/node_modules/eslint/lib/api.js:11:17)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.requireESLint (/Users/gideon/.atom/packages/linter-eslint/lib/linter-eslint.coffee:221:12)
  at Object.provider.lint (/Users/gideon/.atom/packages/linter-eslint/lib/linter-eslint.coffee:96:32)
  at promises.push.Promise.then._this.emitter.emit.linter (/Users/gideon/.atom/packages/linter/lib/linter-registry.js:95:28)
  at /Users/gideon/.atom/packages/linter/lib/linter-registry.js:94:25
  at Set.forEach (native)
  at LinterRegistry.lint (/Users/gideon/.atom/packages/linter/lib/linter-registry.js:92:20)
  at /Users/gideon/.atom/packages/linter/lib/linter.coffee:88:16
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/gideon/.atom/packages/linter/lib/editor-linter.js:100:23
  at /Users/gideon/.atom/packages/linter/lib/helpers.coffee:23:18
```

**Comment by kjohnstoncbt** [comment]
I am seeing this as well with 3.2.0.

**Comment by nilgradisnik** [comment]
Same issue here `3.2.0` on Fedora 22 Linux, Atom `1.0.19`.

**Comment by enjikaka** [comment]
I am too getting this error on OSX

**Comment by sylistine** [comment]
Same issue, Atpm v1.1.0 on Win7

**Comment by jhartma** [comment]
Same issue.

You can get around it if you go to ```Atom Settings``` > ```Open Config Folder``` then go to the ```packages``` folder, then ```linter-eslint``` > ```lib``` and open ```linter-eslint.coffee```. When you comment ```{allowUnsafeNewFunction} = require 'loophole'``` out, the error disappears.

A fix would be appreciated though

**Comment by acemtp** [comment]
This issue strike back when I updated atom (1.1.0) and linter-eslint on Mac os x el captain

**Comment by m9dfukc** [comment]
Jep, same here. Issue is back.

Atom 1.1.0
Mac Osx El Capitain
Linter-eslint 3.2.0

**Comment by mrapczynski** [comment]
+1

**Comment by davezuko** [comment]
Same issue, only works when eslint is installed locally to the project.

**Comment by jcreamer898** [comment]
![](http://d.pr/i/10RoS+)

**Comment by Jarema** [comment]
Same here

osx 10.11 
atom 1.1.0

installing eslint locally solves the problem.

**Comment by jonatasleon** [comment]
Here too

ubuntu 14.04
atom 1.1.0

**Comment by escolhatecnologia** [comment]
same  error

Ubuntu: 15.10
Atom 1.1.0
linter-eslint: 4.0.0
node 5.0


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
  at Function (native)
  at Function.line.toFunction 

.atom/packages/linter-eslint/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55:21)

**Comment by sylistine** [comment]
Can anyone explain or link to something about 'installing locally to project'?

**Comment by enjikaka** [comment]
I reinstalled eslint globally (ran `npm install eslint -g`) and then it worked for me.

**Comment by kundralaci** [comment]
Same problem here, with Atom 1.1, linter installed globally.

**Comment by Pipeman** [comment]
+1 on Mac OS X Yosemite
Appeared right after updating the package linter-eslint and linter

**Comment by thykka** [comment]
I'm getting this error with Atom 1.1.0 and eslint v1.2.1, running on OS X 10.11.1

**Comment by caliber01** [comment]
The same error Ubuntu 14.04, Atom 1.0.19

**Comment by acemtp** [comment]
sudo npm update -g

fixed the problem for me.

**Comment by jameswlane** [comment]
https://github.com/AtomLinter/linter-eslint/issues/99#issuecomment-153044785

**Comment by antigirl** [comment]
same +1

**Comment by WadeWarren** [comment]
me too :+1:

**Comment by thibmaek** [comment]
Damn seems this is definitely a bug bug for everyone.
Same here using OS X 10.11 / Node 4.2.2 / NPM 3.3.12 / Atom latest / Eslint 1.9.0

Problem occurred after upgrading from 4.2.1 to 4.2.2, was working fine in Capitan before.
Reinstalling eslint fixed it.

**Comment by SpainTrain** [comment]
> Damn seems this is definitely a bug bug for everyone.

Not everyone, though it certainly seems to affect a __ton__ of folks.  I haven't been able to repro locally and really haven't seen a pattern in environments of those reporting, which doesn't provide a clear starting point to debug.

For reference, my environment is:

###### system

* Ubuntu 15.10 64-bit (Linux 4.2.0-18)
* atom: 1.1.0
* node: 4.2.2
* npm 3.3.2

###### apm

`apm ls`

```
/home/spainhower/.atom/packages (33)
...
├── linter@1.10.0
...
├── linter-eslint@4.0.0
...
```

`apm -v`

```
apm  1.1.1
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.0
```

###### config.cson

```
...
"linter-eslint":
    showRuleIdInMessage: true
    globalNodePath: "~/npm"
    disableWhenNoEslintrcFileInPath: true
...
```

###### project

* eslint 1.9.0

`npm ls depd`

```
├─┬ express@4.13.3
│ └── depd@1.0.1 
├─┬ karma@0.13.15
│ └─┬ body-parser@1.14.1
│   └── depd@1.1.0 
```

Any thoughts @iam4x @steelbrain @Arcanemagus ?

**Comment by steelbrain** [comment]
@SpainTrain If I had to guess, it's because we're trying to use the renderer process as the eslint process. If we invoke electron with env var `ATOM_SHELL_INTERNAL_RUN_AS_NODE` set to `1` and then invoke eslint from there, it'll work all fine. As a `workaround`, we could use the atom-specific `allowUnsafeEval` :wink:

**Comment by SpainTrain** [comment]
Current best suggestion for those experiencing this seems to be __try reinstalling eslint__ (worked for a couple folks).

**Comment by steelbrain** [comment]
Be advised everybody, I'm rewriting this package to use pure node threads and it should be published very soon, it'll hopefully fix this and any other bugs in this package

**Comment by steelbrain** [comment]
Fixed by v5.0.0

**Comment by ilikescience** [comment]
@steelbrain Looks like this is still happening in Atom 1.5.4 :(

**Comment by steelbrain** [comment]
@ilikescience Can you post your trace in a separate issue? Also make sure you're on the latest version of the package

**Comment by ilikescience** [comment]
@steelbrain done!

**Comment by shamansir** [comment]
Occurs for me with the `eval` existing in the package I use and located in `node_modules`:

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'". at Parser.compile (/Users/shamansir/Workspace/.../node_modules/binary-parser/lib/binary_parser.js:283:21) 
```

`apm ls`:

```
├── linter@1.11.18
```

`apm -v`:

```
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.6.2
```

*Can not* install `npm install --save linter-eslint`, since I get:

```
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "linter-eslint"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0

npm ERR! Cannot convert undefined or null to object
```

The complete log for the latter is here: https://github.com/npm/npm/issues/9896#issuecomment-267474027

**Comment by shamansir** [comment]
I've resolved my case with patching [shamansir/binary-parser](http://github.com/shamansir/binary-parser) with [atom/loophole](http://github.com/atom/loophole) in a branch `with-loophole`. I was able to do it, since the first mentioned repo is my fork of the original [keichi/binary-parser](http://github.com/keichi/binary-parser).

Then, I've changed the version of the dependency in my plugin to use this specific branch in `package.json`:

```javascript
"dependencies": {
    "binary-parser": "git://github.com/shamansir/binary-parser.git#with-loophole"
},
```

Actually, in my case there was another step in-between, since my Atom Plugin Project uses another repo, which, in its case, uses this `binary-parser`: I was required to update this "another repo" to use patched version of `binary-parser` first, then update my Plugin to use the newest version of this "another repo". So anyway it requires a chains of updates, the access to all repos, it's complicated, and no guarantee the PR with `loopback` will be merged to the original repo at any point. 

But Eval is Evil. So someone should suffer :).
