### ISSUE TITLE
v5.0.0 Cannot read property 'match' of undefined at TokenizedBuffer.module...

### ISSUE THREAD

**Issue by glued** [AtomLinter/linter-eslint#263]
linter-eslint v5.0.0

![image](https://cloud.githubusercontent.com/assets/1124158/11165123/ee6819e0-8aba-11e5-83d3-4bf3a11557a4.png)

Atom v1.2.0
ESLint v1.9.0
babel-eslint v4.1.5 

.eslintrc 
```
{
  "parser": "babel-eslint",
  "rules": {
    "strict": 0,
    "quotes": [1, "single"],
    "no-multi-spaces": 0,
    "no-unexpected-multiline": 0,
    "curly": 0,
    "consistent-return": 0,
    "no-underscore-dangle": 0,
    "no-console":0
  },
  "env": {
    "browser": true,
    "node": false
  },
  "globals": {}
}
```
might be related to
https://github.com/AtomLinter/linter-eslint/issues/252

**Comment by Arcanemagus** [comment]
Does this only happen when you have folded part of the code? As I commented over on the other issue I'm pretty sure this is an Atom bug (but have been unable to reproduce it...).

**Comment by glued** [comment]
Not sure what you mean by "folded part of the code". But I get this error on all .js files in atom.
On a side note, I updated linter-eslint to v5 at the same time as updating atom to v1.2.0

**Comment by Arcanemagus** [comment]
In the gutter (line number area) you should have "folder markers" around code blocks, but it sounds like you aren't using that so nevermind.

**Comment by steelbrain** [comment]
If I had to guess, it's an atom bug, because the error is being thrown from it's API

**Comment by marcoms** [comment]
I have the same error on 5.0.1

**Comment by steelbrain** [comment]
@marcoms It's an atom issue, I'll ask in slack about a solution or a workaround

**Comment by dwelle** [comment]
Same on `5.1.0`

**Comment by Arcanemagus** [comment]
Looks like this is the issue: https://github.com/atom/atom/issues/7418

I've commented there exactly what the problem is, we'll see how long it takes to get it fixed in core. I'm not sure we can "properly" work around this as I think doing the same functionality ourselves might involve private methods...

**Comment by dwelle** [comment]
@steelbrain so we need to use the alternative atom-linter to work around this? Using the default, `"parser": "babel-eslint"` still throws.

**Comment by steelbrain** [comment]
@dwelle This has been fixed in the latest release. I tested using the same parser by the way

**Comment by dwelle** [comment]
Is it published? linter-eslint `5.2.0` with linter `1.11.2` and `babel-eslint` parser still throws for me :/

```
TypeError: Cannot read property 'match' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (\AppData\Local\atom\app-1.2.0\resources\app.asar\src\tokenized-buffer.js:669:23)
    at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (\AppData\Local\atom\app-1.2.0\resources\app.asar\src\display-buffer.js:591:35)
    at TextEditor.module.exports.TextEditor.indentLevelForLine (\AppData\Local\atom\app-1.2.0\resources\app.asar\src\text-editor.js:2259:33)
    at TextEditor.module.exports.TextEditor.indentationForBufferRow (\AppData\Local\atom\app-1.2.0\resources\app.asar\src\text-editor.js:2231:19)
    at Object.module.exports.Helpers.rangeFromLineNumber (/.atom/packages/linter-eslint/node_modules/atom-linter/lib/helpers.coffee:64:30)
    at /.atom/packages/linter-eslint/lib/main.js:143:35
    at Array.map (native)
    at /.atom/packages/linter-eslint/lib/main.js:142:27
```

**Comment by steelbrain** [comment]
@dwelle I am using the same parser and it is still working for me I would try to investigate it once more

**Comment by Arcanemagus** [comment]
Published in v5.2.1. (Hopefully for good this time :stuck_out_tongue:)

**Comment by dwelle** [comment]
:+1: works for me
