### ISSUE TITLE
.eslintrc extends fails

### ISSUE THREAD

**Issue by AVVS** [AtomLinter/linter-eslint#280]
it says that it cant find module "eslint-config-airbnb" when .eslintrc is the following one:

```json
{
   "extends": "airbnb"
}
```

Version 4.0.0 works fine

**Comment by steelbrain** [comment]
It's working perfectly fine for me, are you using local eslint or global eslint? Where have you installed `eslint-config-airbnb` module?

**Comment by AVVS** [comment]
Locally installed eslint, as well as a locally installed eslint-config-airbnb. my devDependencies:

```
  "devDependencies": {
    "babel-core": "^5.8.33",
    "babel-eslint": "^4.1.5",
    "chai": "^3.4.1",
    "eslint": "^1.9.0",
    "eslint-config-airbnb": "^1.0.0",
    "eslint-plugin-mocha": "^1.1.0",
    "eslint-plugin-react": "^3.8.0",
    "json": "^9.0.3",
    "mocha": "^2.3.3"
  },
```

**Comment by steelbrain** [comment]
Can you please show us your `linter-eslint` config?

**Comment by AVVS** [comment]
Hm, this is weird, I've updated to 5.1.0 to test it once again. Seemed that I was on 5.0.x yesterday and had that issue, not it seems to be gone. I'll take a closer look at what was happening earlier and reopen it if this occurs again.

Thanks for prompt response anyway!

**Comment by Arcanemagus** [comment]
v5.0.1 and below didn't use a locally installed `eslint`, I'm guessing you were hitting that which was fixed in v5.0.2.

**Comment by tinchoz49** [comment]
Hi @steelbrain, in v5.2.0 i have one case where i'm still getting the error using local plugin extends. 

I'm working in a browserify project where i have the next folder structure:

```
node_modules/
src/
    components/
    styles/
    node_modules/
    index.js
.eslintrc
gulpfile.js
package.json
``` 

If i check the gulpfile.js with atom-eslint everthing works great. But if i check the src/index.js atom-eslint is trying to find the eslint config plugin in src/node_modules/ instead of the root node_modules, throwing the error: Error: Cannot find module 'eslint-config-airbnb'

Note: in v4.0.0 is working fine.

**Comment by steelbrain** [comment]
@tinchoz49 Can you open a new bug report for that?

To all the other people in here, has anybody ever seen eslint usage where `.eslintrc` and `node_modules` are in different dir levels? If not, I can alter the logic to look for `node_modules` in the same dir as `.eslintrc`

**Comment by tinchoz49** [comment]
yes @steelbrain no problem and i agree about to look for node_modules in the same dir as .eslintrc

**Comment by SpainTrain** [comment]
> has anybody ever seen eslint usage where .eslintrc and node_modules are in different dir levels?

@steelbrain Yes, I use different `.eslintrc` files in different directories within a project for code that is written for different environments.  For example, in a web app project I have an `.eslintrc` with specific React settings in a react components dir.  It's also a common pattern to use a separate `.eslintrc` file in the test dir to set globals that test runners provide.  These hierarchies are actually a specific feature of eslint (http://eslint.org/docs/user-guide/configuring.html#configuration-cascading-and-hierarchy)

In general I don't think linter plugins should make assumptions that are not already baked into the upstream linters themselves.  IMO, matching upstream linter behavior provides the best developer flexibility/experience and supports the design goal of least surprise.

**Comment by brutalcrozt** [comment]
```
module.exports = {
    "extends": "airbnb",
    "plugins": [
        //"react"
    ]
};
```
it's say no issue

**Comment by Arcanemagus** [comment]
@brutalcrozt this issue is long closed, and rightfully so. If you are experiencing an issue (which from your message it wasn't clear if you were?) can you file a new issue to debug what is going on?

**Comment by brutalcrozt** [comment]
#296
