### ISSUE TITLE
File ignored because of a matching ignore pattern

### ISSUE THREAD

**Issue by albertosantini** [AtomLinter/linter-eslint#401]
I gave a try to `2.0.0-beta.1`.

With a global setup I get the message `File ignored because of a matching ignore pattern.  Use --no-ignore to override.`

```
  "linter-eslint":
    useGlobalEslint: true
```

Adding disableEslintIgnore, it works correctly.

```
  "linter-eslint":
    disableEslintIgnore: true
    useGlobalEslint: true
```

I am afraid it is not the expected behaviour.
Using the command line there is not need to use that param.

**Comment by Arcanemagus** [comment]
Let's see if I understand this correctly:

* You have a file, let's call it `foo.js`, and this file is _ignored_ in the `.eslintignore` file.
* linter-eslint ignores this file, but gives you a message
* Disabling the handling of `.eslintignore` files makes linter-eslint show errors on the file

How is this not the behavior you were expecting? Are you saying your global `eslint` installation ignores `.eslintignore` files?

**Comment by albertosantini** [comment]
I have not any `.eslintignore` file.

I get that message for any js file using beta.1 version installed globally.

**Comment by albertosantini** [comment]
Recap.

- I have `foo.js`  and I have not a `.eslintignore` file.
- `linter-eslint` ignores this file and gives me that message.
- Disabling the handling of `.eslintignore` files makes linter-eslint show errors on the file

Weirdly, no?

**Comment by Arcanemagus** [comment]
I think I know what is going on here, do you have a `.eslintignore` file in any _parent_ directory? It looks like we are using `helpers.find` to search for it, but not limiting its scope, so it would search up to the filesystem root for that file.

**Comment by albertosantini** [comment]
No, I have not any `.eslintignore` file. I never used the ignore feature.

Neither I am using `.gitignore` in the test case. Just in case
http://eslint.org/blog/2016/01/eslint-v2.0.0-beta.1-released/#eslintignore-changes

(No eslint options in package.json).

The only thing I changed is the version of eslint (2.0.0-beta.1) and the cli works correctly.

I checked the arguments passed to the cli and they are the same (1.10.3 and 2.0.0-beta.1). Of course, eslint-linter is not changed. I checked also eslintignoreDir and it contains "." in both versions.

Output of the cli with DEBUG
```
$ export DEBUG=*                                                                                                                                                                   
09:26:16 [/c/My/Dev/snippets/000]                                                                                                                                                  
$ eslint foo.js                                                                                                                                                                    
...
  eslint:cli Running on files +0ms
  eslint:cli-engine Processing C:\My\Dev\snippets\000\foo.js +62ms
  eslint:cli-engine Linting C:\My\Dev\snippets\000\foo.js +0ms
  eslint:config Constructing config for C:\My\Dev\snippets\000\foo.js +0ms                                                                                                         
  eslint:config Using .eslintrc and package.json files +0ms                                                                                                                        
  eslint:config Loading C:\My\Dev\snippets\000\.eslintrc.yml +16ms                                                                                                                 
...
  eslint:cli-engine Linting complete in: 454ms +0ms                                                                                                                                
                                                                                                                                                                                   
C:\My\Dev\snippets\000\foo.js                                                                                                                                                      
  3:21  error  Missing semicolon  semi                                                                                                                                                                                                                                                                                                                                
```

Just checking the output of the cli with .eslintignore
```
09:30:29 [/c/My/Dev/snippets/000]
$ echo foo.js > .eslintignore
09:30:50 [/c/My/Dev/snippets/000]
$ eslint foo.js                                                                                              
  eslint:cli Running on files +0ms                                                                           
  eslint:cli-engine Linting complete in: 0ms +62ms                                                           
                                                                                                             
C:\My\Dev\snippets\000\foo.js                                                                                
  0:0  warning  File ignored because of a matching ignore pattern. Use --no-ignore to override               
                                                                                                             
✖ 1 problem (0 errors, 1 warning)                                                                            
```

**Comment by mjomble** [comment]
Same here, everything worked on both command line and in Atom with eslint 2.0.0 alpha 2, but as soon as I updated to beta 1, I started getting "File ignored because of a matching ignore pattern. Use --no-ignore to override." in Atom while everything still works on the command line.

**Comment by albertosantini** [comment]
I investigated a bit and really I don't understand because changing only the underlying eslint version we get this behaviour.

However I think we need to check better the following line:
https://github.com/AtomLinter/linter-eslint/blob/master/lib/worker.js#L24

`find` correctly returns `null`, but 
```
> require("path").dirname(null)
'.'
```

That set impacts on the following condition:
https://github.com/AtomLinter/linter-eslint/blob/master/lib/worker.js#L49

Indeed if I set `eslintignoreDir` to `null`, eslint-linter works as expected (I mean, without the workaround `disableEslintIgnore: true`).

At the moment I would be tempted to create a PR like:

```
  const findeslintignoreDir = find(params.fileDir, '.eslintignore')
  const eslintignoreDir = findeslintignoreDir ? Path.dirname(eslintignoreDir) : null
```

What do you think?

**Comment by albertosantini** [comment]
I saw the changes in the refactoring (#373).
https://github.com/AtomLinter/linter-eslint/pull/373/files#diff-ba0b506b21d765d9a942022f3dbdd800R104

Up to you if I need to prepare the PR or you prefer to wait the refactoring lands on the master.

**Comment by steelbrain** [comment]
@albertosantini Can you help us merge it sooner by testing it and telling us if you experience any issues?

**Comment by albertosantini** [comment]
#373 via `compact-codebase` branch tested.
Indeed it fixes this issue.

More details on that branch in #373.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-eslint/pull/367

**Comment by aoberoi** [comment]
i've updated to v6.0.0 of the plugin, which seems like it includes #367, but i'm still having this issue.

**Comment by IanVS** [comment]
@aoberoi what error are you getting?

**Comment by aoberoi** [comment]
@IanVS "File ignored because of a matching ignore pattern. Use --no-ignore to override."

<img width="684" alt="screen shot 2016-02-16 at 10 53 28 pm" src="https://cloud.githubusercontent.com/assets/494795/13102089/3b7229da-d500-11e5-864d-0915a39b69d5.png">

**Comment by IanVS** [comment]
When you say it doesn't appear with the CLI, did you tell eslint to lint specifically that file?  Or just the folder containing it?

**Comment by tomkur** [comment]
I've got same or similar problem. I've ignored a file in ```.eslintignore``` and when I open this file, linter warns me with "File ignored because of a matching ignore pattern". I know it's ignored and I wish not to see these warnings. Is there any workaround?

**Comment by IanVS** [comment]
Hm, I think in general we want to keep that warning (it can be good to know when a file is not being linted because it is ignored), but perhaps we could add a setting like `Do not show ignored file warnings".  What do you think, @Arcanemagus?

**Comment by IanVS** [comment]
Hm, so I guess there's more here than I thought.  We actually _do_ ignore those messages, but a change made to ESLint recently (by none other than myself, turns out), broke our ignore checks.  They are fixed in https://github.com/AtomLinter/linter-eslint/pull/593.  

I wonder if this should still be an option, because I do quite like seeing explicitly when a file is being ignored, rather than it just looking like there are `No Issues`.

**Comment by IanVS** [comment]
I'm going to re-close this as fixed by #593, but I'd like to continue the conversation about whether or not this should be an option.

**Comment by Arcanemagus** [comment]
Looks like it's been that way [from the start](https://github.com/AtomLinter/linter-eslint/pull/287), I'm guessing the reason is that without ignoring them an `eslint` ignored file will always show "1 issue" on it in project scope / status bar, even when the file is ignored.

**Comment by IanVS** [comment]
Yeah, I guess I'm saying that I see value in seeing that "1 issue" for ignored files.  I personally would like to know when a file is open that it's being ignored.  I can see valid reasons for either wanting to see that or not wanting to see it, so an option seems to make sense to me.

**Comment by Arcanemagus** [comment]
Sorry, should have been more clear, I personally would prefer it showing, was just trying to figure out why it was ignored in the first place 😛.

An option controlling that sounds fine to me.

**Comment by tomkur** [comment]
The warning does not disappear when I close the file, which is my main
concern here. Having it while the file is open is acceptable.

W dniu piątek, 10 czerwca 2016 Landon Abney <notifications@github.com>
napisał(a):

**Comment by Arcanemagus** [comment]
@tomkur That would be a linter bug, this package gives it a list of messages, it _should_ be destroying those messages when the related editor is closed for a file scoped linter like this. If you can reproduce that would you mind filing a bug [over there](https://github.com/steelbrain/linter/issues)?

**Comment by tomkur** [comment]
@Arcanemagus Not sure it's a linter bug. I use Atom and when I check "Show only diagnostics for current file", "File ignored" warning disappears when closing file. However, I don't want to check this - I want to see all the errors and warnings. But I don't want the list of errors and warnings be flooded by "File ignored" warning just because I happened to open multiple ignored files and closed them.

**Comment by Arcanemagus** [comment]
@tomkur If you are using `eslint@^2.11.1` the ignored file message was changed, you need to be on v7.2.3 of this package to properly ignore it.

**Comment by gabrielkunkel** [comment]
I wish there was an option to turn off this warning. I like the idea of having the warning as an option, but it's annoying when it's reminding me that I'm skipping yarn.lock. So, I'm only using errors on those things that are critical and the --quiet flag.
