### ISSUE TITLE
Strange error on Linux

### ISSUE THREAD

**Issue by PhiLhoSoft** [AtomLinter/linter-eslint#419]
I have a weird issue, a bit hard to describe...

I use successfully your package with Atom on Windows 7. I made a .eslintrc.yaml file with a number of rules. It has been committed to our VCS.
A co-worker which uses Linux wants to try Atom, and installed this package too. The Yaml file is in his project as well; thanks to VCS...

First issue: the linebreak-style option is ineffective in Atom, because apparently Atom loads the file internally with the native line break.
Let me explain: our files use the Windows line ending style, CR+LF. Don't ask me why... So I have set the above option to `windows`.
But all lines on the co-worker's Atom are marked as bad; and Atom showing invisible chars shows only LFs. So, since that's what your package analyses, all lines are bad.
Note: I had the same problem in Brackets, except it normalizes on LF on Windows... I thought it was solved in Atom.
Side note: the Brackets plugin for ESLint reports only one such error per file, the first found. Less overwhelming...

OK, that's not a major issue, I just set the setting to 0. It works: if I close the file's tab then reopen it, the errors are gone.
But I get a busload of other errors! Like `angular` symbol not defined (while it is in my `globals` section), bad brace placement (while `brace-style` is OK), etc.
That's where I am confused: where does these rules come from? I thought that ESLint provides no rules by default.
It isn't even that it doesn't find the Yaml file, since if I edit it to deactivate the line ending setting, it works...

I see no errors in the console, either.

Is that a known issue?

**Comment by Arcanemagus** [comment]
You `CRLF`/`LF` issue should be solved by your VCS config, all the major ones have the ability to configure what line ending a file is checked out as (regardless of the client OS), I'm guessing you haven't configured this and so it's set to default (which is "whatever the native line endings are for the system" usually).

Without seeing your configuration file it's pretty hard to address the rest of your comment.

**Comment by PhiLhoSoft** [comment]
I think you missed the point on line ending: it is fine on our files, there is no VCS issue, and no need to normalize on commit. It is just that Atom "normalizes" line endings in its internal buffer, so you don't see the real line ending. If I run ESLint on the command line, it doesn't complain about these line endings.
But that's not something you can act upon, I suppose, so my remark is just a heads up.

I didn't include the config file because I feel it is not really part of the problem, but here it is, anyway (as a .txt file to please GitHub).

[.eslintrc.yaml](https://github.com/AtomLinter/linter-eslint/files/108635/default.eslintrc.yaml.txt)

**Comment by Arcanemagus** [comment]
Atom _doesn't_ mess with the line endings in the buffer, hence why I misread that as being the VCS issue. Looking into it to see if somewhere we screw with them before passing to the worker process...

**Comment by Arcanemagus** [comment]
@PhiLhoSoft is this still an issue you are seeing? I was unable to reproduce it when you first reported this problem.

If you are, can you please attach a zip file containing:

* Your ESLint configuration (`.eslintrc.yaml`)
* A file to be linted using that configuration

If I'm understanding the issue correctly, you were seeing no issues when running ESLint in the CLI, but the same file would show issues when opened within Atom, so if you could describe _exacly_ what issues you are seeing in Atom that will be helpful.

**Comment by PhiLhoSoft** [comment]
I am no longer able to reach a Linux computer easily, so I will just close the issue.
