### ISSUE TITLE
Activate Use Global Eslint package option

### ISSUE THREAD

**Issue by backspaces** [AtomLinter/linter-eslint#461]
Blush! I can't find an atom package settings for linter-eslint, so when trying to use eslint globally, I don't know how to do this:

> Activate Use Global Eslint package option

.. which the readme sez to do.

**Comment by steelbrain** [comment]
If you can not find `linter-eslint` setting in Atom Settings View, try this
```
apm uninstall linter-eslint
apm install linter-eslint
```
and then restart Atom

Let me know if it works for you

**Comment by backspaces** [comment]
Fixed it, thanks!

**Comment by gaboesquivel** [comment]
hey tried that and didn't work for me, I still can't see the eslinter under packages dropdown.  How can I set that option from config.cson?

**Comment by Arcanemagus** [comment]
@gaboesquivel You need to go to Settings -> Packages -> linter-eslint.

This package has no commands to run, as such there is no reason for it to be in the Packages menu.
