### ISSUE TITLE
Catch errors from `eslint`

### ISSUE THREAD

**Issue by iam4x** [AtomLinter/linter-eslint#65]
It should be easy to wrap lint fn into a `try catch` for linting

**Comment by iam4x** [comment]
Done with 1.0

**Comment by klapec** [comment]
Unfortunately I am still getting "JS-YAML: missed comma between flow collection entries at line 23, column 53:" errors. Should I open a separate issue or post the details here?

**Comment by hikkyu** [comment]
I am still getting error too

**Comment by Vozf** [comment]
the problem for me was fixed by renaming .eslint to .eslint.js
