### ISSUE TITLE
[Linter] Error running ESLint Error: Cannot find module

### ISSUE THREAD

**Issue by allanchau** [AtomLinter/linter-eslint#974]
## Issue Type

Bug

## Issue Description

The linter cannot find the shareable config in the project root folder `/node_modules/`.
```shell
root
├── .eslintrc
├── node_modules/
├── app/root/app/
│   └── file.js # [Linter] Error running ESLint Error: Cannot find module...
└── file.js     # Working
```
I would expect it to search where the `.eslintrc` is located (root).
I also did some debugging `linter-eslint/node_modules/eslint/lib/util/module-resolver.js:78:19` and the root directory is not passed in the `const result = Module._findPath(name, lookupPaths);`, instead it is searching in `app/root/app/node_modules`.

The weird thing is this only happens for 1 of my projects?

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [ ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below
This command doesn't seem to work for me.

```
Linter Eslint: Debug output here
helpers.js:138 Uncaught (in promise) TypeError: Cannot read property 'atomVersion' of undefined(…)(anonymous function) @ helpers.js:138step @ helpers.js:9(anonymous function) @ helpers.js:9_tickCallback @ internal/process/next_tick.js:103
```

**Comment by IanVS** [comment]
Hm, interesting.  Would you be able to make a minimal reproducible case for this bug?  Either a repo, or a zip file or something?  That would help us a lot.

**Comment by allanchau** [comment]
@IanVS Sure, this is failing for me now too.
[eslint-test-v1.0.0.tgz.zip](https://github.com/AtomLinter/linter-eslint/files/1204676/eslint-test-v1.0.0.tgz.zip)

**Comment by IanVS** [comment]
I tried it out, and was getting an error:

```
Error while loading rule 'eslint-comments/no-unused-disable': Cannot read property 'report' of undefined
```

Which is being thrown from the `eslint-comments/no-unused-disable` rule due to a bug that was fixed in version `1.0.3` of that package.  I've submitted a PR to your shared config which fixes that error.  When I run with version `1.0.3` in the files you shared, I get two seemingly valid lint errors within `app/root/app/index.js`, so it seems perhaps something else is going on.  What are your linter-eslint settings?

Also, this could be a bug with setting the cwd correctly.  Can you try adding an `.eslintignore` file at your main project root?  https://github.com/AtomLinter/linter-eslint/pull/965 has been merged but not yet released, and it may also help your problem.  But I'm just shooting in the dark because I can't reproduce the issue you're having.

**Comment by allanchau** [comment]
I'm just using the stock settings:
`Disable when no ESLint config is found (in package.json or .eslintrc)` and `Show Rule ID in Messages`.

The `.eslintignore` didn't fix it unfortunately, but setting `node_modules` as the `Path to the local node_modules folder` did!

**Comment by IanVS** [comment]
I'm glad you were able to find a workaround.  If you want us to keep looking into the issue, feel free to supply another set of files that will reproduce the issue on a fresh install.  In the meantime, since you seem to be back up-and-running, I'm going to close this issue.  Thanks for the report.

**Comment by rahulmanas** [comment]
Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
Error: Cannot find module '/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/api.js/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.module.exports (/node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js:170:23)

Using below dependencies:

"@vue/cli-plugin-babel": "^3.0.4",
    "@vue/cli-plugin-eslint": "^3.0.4",
    "@vue/cli-service": "^3.0.4",
    "@babel/core": "^7.0.0",
    "babel-plugin-istanbul": "^4.1.1",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-eslint": "^7.0.0",

 "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-2": "^6.22.0",

I am stuck as when i am trying to setup the system to do the API call. For that ESLINT is required. Can anyone help me with it??

I also tried these:
"eslint": "^3.19.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-html": "^3.0.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",

I am new at this. And i have no idea which version to use. Its really pain to figure out which version is correct.

Any leads is appreciated.

Thanks in advance!
